- 계층(Layer)
- 모듈(Module) : 레이어 그룹화
- 모델(Model) : 모듈 그룹화 (한 개의 모듈이 모델 가능)

## 단층 퍼셉트론
``` 
f(x) = x * W + b 가정

x1 -> y1 가는 b1
x4 -> y1 가는 b4

b1 + b2 + b3 + b4 = b1 으로 고정
(출력 y1으로 가는 b는 b1)

입력4, 출력3, 가중치12
```

### x,b  열벡터 

In [7]:
import torch

x = torch.FloatTensor(4) # 입력
W = torch.FloatTensor(4,3) # 가중치
b = torch.FloatTensor(3) # 편향

### vector * matrix
```
vector 전치 이후 * matrix
```

In [8]:
import torch

def linearfunction(x,W,b):
    y = torch.matmul(x,W) + b
    return y

```
출력 3
```

In [9]:
y = linearfunction(x, W, b)
y.shape

torch.Size([3])

## Class
```
__init__ : 신경망 계층 초기화 선언

init 메소드 안에서 값 선언해야함
```

In [35]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.W = torch.FloatTensor(4,3)
        self.b = torch.FloatTensor(3)
    
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        
        return y

In [36]:
x = torch.FloatTensor(4)

linear = NeuralNetwork()

y = linear(x)

In [37]:
print(y, y.shape)

tensor([3.6893e+19, 1.7628e+00, 5.2762e+00]) torch.Size([3])


### 입력 차원, 출력 차원 직접 입력 X

In [38]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
    
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        
        return y

In [42]:
x = torch.FloatTensor(10)

linear = NeuralNetwork(10,5)

y = linear(x)

In [43]:
print(y, y.shape)

tensor([4.2890e-08, 1.0073e-11, 8.5084e-07, 8.3384e-10, 1.0720e-08]) torch.Size([5])


## nn.Parameter 파라미터 등록
```
self 인자로 받은거 nn.Parameter 로 묶어주면 됨.
```

In [44]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
    
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        
        return y

In [49]:
x = torch.FloatTensor(5)

linear = NeuralNetwork(5,3)

y = linear(x)

In [50]:
print(y, y.shape)

for param in linear.parameters():
    print(param)

tensor([0.0000e+00, 0.0000e+00, 7.0065e-45], grad_fn=<AddBackward0>) torch.Size([3])
Parameter containing:
tensor([[1.0561e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]], requires_grad=True)
Parameter containing:
tensor([0.0000e+00, 0.0000e+00, 7.0065e-45], requires_grad=True)


## nn.Linear

In [58]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        
        self.linear = nn.Linear(input_dim, output_dim)
    
    def forward(self, x):
        y = self.linear(x)
        
        return y

In [60]:
x = torch.FloatTensor(4)
linear = NeuralNetwork(4,3)
y = linear(x)

In [61]:
print(y, y.shape)

for param in linear.parameters():
    print(param)

tensor([-0.1837, -0.4018, -0.1354], grad_fn=<AddBackward0>) torch.Size([3])
Parameter containing:
tensor([[ 0.1365,  0.1326, -0.3312,  0.4827],
        [ 0.3383, -0.4727,  0.2885, -0.1034],
        [-0.0785,  0.2394, -0.0202,  0.3565]], requires_grad=True)
Parameter containing:
tensor([-0.1837, -0.4018, -0.1354], requires_grad=True)
