In [4]:
import torch

### scala (0D 텐서)

In [7]:
import numpy as np
data1 = np.array(10)
print(data1, data1.ndim, data1.shape)

10 0 ()


### vector (1D 텐서)

In [11]:
import torch
data1 = torch.FloatTensor([1,2])
print(data1, data1.dim(), data1.shape)

data2 = torch.FloatTensor(3)
print('\n',data2, data2.dim(), data2.shape)

tensor([1., 2.]) 1 torch.Size([2])

 tensor([1.4013e-45,        nan, 2.6995e-18]) 1 torch.Size([3])


### metrix (2D 텐서)
* data.shape : torch.Size ([가로 묶음 개수, 묶음의 묶음 개수])

In [17]:
data3 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(data3, data3.dim(), data3.shape)

data4 = torch.FloatTensor(3,2)
print('\n', data4, data4.dim(), data4.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) 2 torch.Size([2, 3])

 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


### 3D 텐서
* data.shape : torch.Size ([가로 묶음 개수, 묶음의 묶음 개수, 층수])

In [37]:
data5 = torch.FloatTensor(2,3,3,1)
print(data5, data5.dim(), data5.shape)

data6 = torch.FloatTensor([[[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]],
                          [[[10],[11],[13]],[[14],[15],[16]],[[17],[18],[19]]]])
print(data6, data6.dim(), data6.shape)

print(data6 + data5)

tensor([[[[ 1.],
          [ 2.],
          [ 3.]],

         [[ 4.],
          [ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.],
          [ 9.]]],


        [[[10.],
          [11.],
          [13.]],

         [[14.],
          [15.],
          [16.]],

         [[17.],
          [18.],
          [19.]]]]) 4 torch.Size([2, 3, 3, 1])
tensor([[[[ 1.],
          [ 2.],
          [ 3.]],

         [[ 4.],
          [ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.],
          [ 9.]]],


        [[[10.],
          [11.],
          [13.]],

         [[14.],
          [15.],
          [16.]],

         [[17.],
          [18.],
          [19.]]]]) 4 torch.Size([2, 3, 3, 1])
tensor([[[[ 2.],
          [ 4.],
          [ 6.]],

         [[ 8.],
          [10.],
          [12.]],

         [[14.],
          [16.],
          [18.]]],


        [[[20.],
          [22.],
          [26.]],

         [[28.],
          [30.],
          [32.]],

         [[34.],
          [36.],
   

## 텐서간 곱셈 정리

### 1D 텐서 x 1D 텐서
* 차원이 같아야 계산 가능

In [39]:
import torch

A = torch.full((3,),2)
B = torch.full((3,),3)

print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)

result = torch.matmul(A,B)
print(result, result.shape) # 0D 텐서 (스칼라 값)

tensor([2, 2, 2]) 1 torch.Size([3])
tensor([3, 3, 3]) 1 torch.Size([3])
tensor(18) torch.Size([])


### 2D 텐서 x 2D 텐서
* 앞 행렬의 열의 수 = 뒷 행렬의 행의 수, 조건 성립시 계산 가능

In [42]:
A = torch.full((3,2),2)
B = torch.full((2,3),3)

print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)

result = torch.matmul(A,B)
print(result, result.shape)

tensor([[2, 2],
        [2, 2],
        [2, 2]]) 2 torch.Size([3, 2])
tensor([[3, 3, 3],
        [3, 3, 3]]) 2 torch.Size([2, 3])
tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]) torch.Size([3, 3])


### 1D 텐서 x 2D 텐서
* torch.full((x,y),z) , z=안에 넣을거, y = 몇 묶음, x = 몇 줄

In [51]:
x = torch.full((3,), 2)
A = torch.full((3,2), 3)

result = torch.matmul(x,A)
print(x, A)
print(result, result.shape)

tensor([2, 2, 2]) tensor([[3, 3],
        [3, 3],
        [3, 3]])
tensor([18, 18]) torch.Size([2])


### 2D 텐서 x 1D 텐서

In [55]:
a = torch.full((4,3,2),3)
a

tensor([[[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]]])

In [61]:
data1 = torch.full((10,8,3,4),2)
data2 = torch.full((2,4,5),3)
data1

tensor([[[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2